apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: myapi
  description: The official Spotify REST API
spec:
  type: openapi
  lifecycle: production
  owner: spotify
  definition:
    $text: openapi.yaml
